FROM node:14

COPY . code
WORKDIR code
# fix https://stackoverflow.com/questions/65288750/docker-container-npm-err-internal-watch-failed-circular-symlink-detected
RUN echo "{'ext': 'js'}" >> nodemon.js

RUN yarn
CMD ["yarn", "dev"]

