FROM  maven:3-jdk-8-alpine
COPY . backend
RUN cd backend/delivery-service/src/main/resources/ && cp application-dev.properties application.properties
RUN cd backend && mvn -B -DskipTests -DfinalName=ROOT --projects delivery-service --also-make package
CMD ["java","-jar","backend/delivery-service/target/deliveryservice.jar"]
