services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      CDN_SERVER_PORT: ${CDN_SERVER_PORT}
      _JAVA_OPTIONS: ${JAVA_OPTIONS}
    volumes: 
      - /var/docker/odh-webcompstore-cdn/shared/workspace:/workspace
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${API_SERVER_PORT}/actuator/health"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    ports:
      - "${CDN_SERVER_PORT}:${CDN_SERVER_PORT}"
      