services:
  api:
    container_name: data-service
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
      target: build
    env_file: 
      - .env
    volumes:
      - ../../.m2:/code/.m2
        