FROM  maven:3-jdk-8-alpine
COPY . backend
RUN cd backend/data-service/src/main/resources/ && cp application-dev.properties application.properties
RUN cd backend && mvn -B -DskipTests -DfinalName=ROOT --projects data-service --also-make package
CMD ["java","-jar","backend/data-service/target/dataservice.jar"]



