FROM maven:3.6.1-jdk-11

ARG JENKINS_GROUP_ID=1000
ARG JENKINS_USER_ID=1000

RUN addgroup --gid $JENKINS_GROUP_ID jenkins && \
    adduser --disabled-password -u $JENKINS_USER_ID --group jenkins jenkins

COPY docker/entrypoint-java.sh /entrypoint-java.sh

ENTRYPOINT [ "/entrypoint-java.sh" ]
